### PR TITLE
Circleci project setup

### PR DESCRIPTION
**Pull request by red15**
Putting forward a simple circleci benchmark.
Can still be refined further but would server as a good baseline to compare builds.

### CODE REVIEW

**Comment by avinassh** [comment]
Thank you for this PR! Setting up CI would help us in having a baseline to compare before and after results. Could you tell me how do I set this up? I believe I need to create an account on Circle CI and then connect with this repo? 

Secondly, whats the numbers look like at Circle CI? Earlier I had added Github Workflow, but it was very slow, I think it took about an hour for the basic rust version. I am assuming that was because of the low CPU powered CI/CD machines.

**Comment by red15** [comment]
Can you not see the results at https://app.circleci.com/pipelines/github/red15/fast-sqlite3-inserts?branch=circleci-project-setup
Signing up for CircleCI is just an Oauth token from your Github. No cost or real hard signup imho.

Currently the rust is failing on the threaded_batch test (might be some CI limitation on thread cpu usage) which we can sort out later (possibly splitting threaded vs basic into their own tests or reducing the record count)

I'd recommend for rust to switch to proper benchmark setup using [Criterion](https://crates.io/crates/criterion) which can properly handle the cases with and without zipcode and compare them properly.

**Comment by avinassh** [comment]
Signed up and I can see the benches.

> Currently the rust is failing on the threaded_batch test (might be some CI limitation on thread cpu usage) which we can sort out later (possibly splitting threaded vs basic into their own tests or reducing the record count)

```shell
#!/bin/bash -eo pipefail
time ./target/release/threaded_batched
/bin/bash: line 1:  5040 Killed                  ./target/release/threaded_batched

real	1m0.432s
user	0m24.713s
sys	0m30.960s

Exited with code exit status 137
CircleCI received exit code 137
```

it seems OOM issue - https://support.circleci.com/hc/en-us/articles/115014359648-Exit-code-137-Out-of-memory 

> we can sort out later (possibly splitting threaded vs basic into their own tests or reducing the record count)

I would prefer fixing the issues and then merging them to the mainline :D 

one thing we could do is check for 10M or 50M inserts in CI. 

> I'd recommend for rust to switch to proper benchmark setup using Criterion which can properly handle the cases with and without zipcode and compare them properly.

checked out creterion, looks good to me. Would like to send a PR?

**Comment by avinassh** [comment]
I am realising one mistake I did was hardcoding 100M in the code 🤔

**Pull request closed without merging**
